apiVersion: v1
kind: Service
metadata:
  label:
  name: nginx-rs-nodeport-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 81 # Listening port on ClusterIP
    targetPort: 8080 # Pod’s listening port
    nodePort: 32080
    protocol: TCP
  selector:
    app: nginx-rs-pod

