apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-test
spec:
  replicas: 1
  selector:
    app: nginx-test
  template:
    metadata:
      name: nginx-test
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
